#################
### AUTOSTART ###
#################

# ================================
# SYSTEM SERVICES & ENVIRONMENT
# ================================
exec-once = systemctl --user start pipewire
exec-once = systemctl --user start plasma-polkit-agent
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


# ================================
# WALLPAPER & THEMING
# ================================
exec-once = swww-daemon --transition-fps 60 --transition-step 2
exec-once = "~/.config/swww/rand_wall.sh"
# exec-once = "~/.config/hypr/scripts/swww_parallax_effect.sh"
# exec-once = ~/.config/swww/swww_custom.sh ~/Pictures/wallpapers/walls-catppuccin-mocha/

# ================================
# CURSOR THEME
# ================================
exec-once = hyprctl setcursor HyprBibataModernClassicSVG 30
# exec = hyprctl setcursor catppuccin-macchiato-peach-cursors 30

# ================================
# UI COMPONENTS
# ================================
exec-once = hyprpanel
exec-once = hyprpm reload
exec-once = hypridle
exec-once = eww
# exec-once = waybar & mako
# ================================
# SYSTEM TRAY APPLETS
# ================================
exec-once = nm-applet & blueman-applet
exec-once = udiskie

# ================================
# CLIPBOARD MANAGEMENT
# ================================
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# ================================
# OTHER UTILITIES
# ================================
# exec-once = hyprdim --strength 0.4 --duration 600 --fade 6 --bezier wind --dialog-dim 0.7
# exec-once = ianny

